name: ecommerce_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

#------------------- PACKAGES-------------------#
dependencies:
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  get_storage: ^2.1.1
  iconsax: ^0.0.8
  intl: ^0.19.0
  logger: ^2.2.0
  readmore: ^3.0.0
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.6
  flutter_rating_bar: ^4.0.1

#Product Specific
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # ---------------- LOCAL ASSETS ----------------
  assets:
    - assets/logos/
    - assets/icons/categories/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/reviews/
    - assets/images/animations/
    - assets/images/content/
    - assets/images/on_boarding_images/
    - assets/icons/payment_methods/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
